config/routes.rb
Todolist::Application.routes.draw do

  resources :lists do
    resources :tasks
  end
  
  match "lists/:list_id/tasks/:id/complete" => "tasks#complete", :as => :complete_task 

  root :to => "lists#index"

end

app/models/list.rb
class List < ActiveRecord::Base

  validates :name, :presence => true
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :list

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  respond_to :html, :xml, :js
  
  def index
    respond_with(@lists = List.all)
  end  

  def new
    @list = List.new
  end  
  
  def create
    @list = List.new(params[:list])
    if @list.save
      flash[:notice] = "List created."
      respond_with(@list, :location => list_url(@list))
    else
      flash[:error] = "Could not create list."
      redirect_to new_list_url
    end  
  end  

  def show
    @list = List.find(params[:id])
    @task = @list.tasks.new
  end
  
  def edit
    @list = List.find(params[:id])
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      flash[:notice] = "List updated."
      respond_with(@list, :location => list_url(@list))
    else
      flash[:error] = "Could not update list."
      redirect_to edit_list_path(@list)
    end
  end
  
  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash[:notice] = "List deleted."
      redirect_to lists_url
    else
      flash[:error] = "Could not delete list.  Have you done everything?"
      redirect_to lists_url
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  attr_accessor :completed
  before_filter :find_list
  respond_to :html, :xml, :js
  
  def create
    @task = @list.tasks.new(params[:task])
    if @task.save
      flash[:notice] = "Task created."
      redirect_to list_url(@list)
    else
      flash[:error] = "Could not add task."
      redirect_to list_url(@list)
    end
  end
  
  def complete
    @task = @list.tasks.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to list_url(@list)
  end
  
  private 
  
  def find_list
    @list = List.find(params[:list_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Todolist</title>
	<%= stylesheet_link_tag :all %>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/base/jquery-ui.css" %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js" %>
	<%= csrf_meta_tag %>
</head>
<body>
<% if flash[:error] %>
	<div class="ui-state-error ui-corner-all flash-error" style="padding: 0.7em;">
		<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span><strong>Error:</strong> <%= flash[:error] %></p>
	</div>
<% end %>

<% if flash[:notice] %>
	<div class="ui-state-highlight ui-corner-all flash-notice" style="margin-top: 20px; padding 0.7em;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span><%= notice %></p>
	</div>
	
<% end %>

<div id="main-body">
<%= yield %>
</div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |form| %>
	
	<label>Name:
		<p><%= form.text_field :name %></p>
	</label>
	
	<label>Description:
		<p><%= form.text_field :description %></p>
	</label>
	
	<p><%= form.submit %></p>	
	
<% end %>

app/views/lists/edit.html.erb
<h1>Edit this list</h1>

<%= render :partial => "form" %>

app/views/lists/index.html.erb
<h1>My Todo Lists</h1>

<% @lists.each do |list| %>
	
	<h2><%= link_to "#{list.name}", list_url(list) %></h2>
	<p><%= list.description %> - <%= link_to "Edit", edit_list_url(list)%> | <%= link_to "Delete", list, :confirm => "Are you sure?", :method => :delete %></p>
	
<% end %>	

<hr />

<%= link_to "Add new list", new_list_url %>

app/views/lists/new.html.erb
<h1>New Todo List</h1>

<%= render :partial => "form" %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><%= @list.description %></p>

<ul>
	<% @list.tasks.each do |task| %>
		<li><%= task.description %> - <%= button_to "Complete", complete_task_path(@list.id, task.id) %></li>
	<% end %>
</ul>

<%= form_for [@list, @task] do |form| %>

<p><%= form.text_field :description %> <%= form.submit %></p>

<% end %>

<hr />
<%= link_to "Back to all lists", lists_url %>